---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    osx_script: ./files/osx.sh

    mas_installed_apps:
      - { id: 405843582, name: "Alfred" }
      - { id: 441258766, name: "Magnet" }
      - { id: 897283731, name: "StrongBox" }
      - { id: 1221250572, name: "Xnip" }
      - { id: 824183456, name: "Affinity Photo" }
      - { id: 1518425043, name: "Boop" }
      - { id: 1447043133, name: "CursorPro" }
      - { id: 1444383602, name: "GoodNotes 5" }
      - { id: 905953485, name: "NordVPN" }
      - { id: 824171161, name: "Affinity Designer" }
      - { id: 881418622, name: "Affinity Publisher" }
      - { id: 1534275760, name: "Languagetool" }

    homebrew_installed_packages:
      - alacritty
      - ansible-lint
      - argo
      - argocd
      - azure-cli
      - awscli
      - bat
      - cmake
      - coreutils
      - datawire/blackbird/telepresence-legacy
      - direnv
      - dive
      - dog
      - dua-cli
      - duf
      - entr
      - exa
      - fd
      - findutils
      - fluxcd/tap/flux
      - fluxctl
      - fzf
      - gh
      - git-delta
      - git-filter-repo
      - gitui
      - glow
      - gnu-tar
      - go
      - golangci-lint
      - gomodifytags
      - gopass
      - goreleaser
      - gron
      - hadolint
      - hashicorp/tap/terraform-ls
      - helm
      - hledger
      - htop
      - httpie
      - hugo
      - hurl
      - imagemagick
      - infracost
      - ipython
      - isync
      - jenv
      - jq
      - jupyterlab
      - k6
      - k9s
      - khal
      - khard
      - kind
      - koekeishiya/formulae/skhd
      - koekeishiya/formulae/yabai
      - kube-linter
      - kubeconform
      - kubectx
      - kubeseal
      - kubeval
      - kyverno
      - latexindent
      - lazydocker
      - lazygit
      - lf
      - lua-language-server
      - luarocks
      - mdbook
      - miller
      - mitmproxy
      - moreutils
      - msmtp
      - mysql-client
      - neomutt
      - neovim
      - neovim-remote
      - newsboat
      - nmap
      - nnn
      - notmuch
      - notmuch-mutt
      - npm
      - openjdk@11
      - openjdk@17
      - pandoc
      - pdfgrep
      - prettier
      - pulumi
      - pwgen
      - rcm
      - ripgrep
      - session-manager-plugin
      - shellcheck
      - sketchybar
      - slides
      - stern
      - stylua
      - tectonic
      - terraform-docs
      - texlab
      - tflint
      - tig
      - tmux
      - tokei
      - trash-cli
      - tree
      - urlview
      - vale
      - vdirsyncer
      - viddy
      - vifm
      - w3m
      - wget
      - xclip
      - yq
      - yt-dlp
      - zoxide

    homebrew_uninstalled_packages: []

    homebrew_taps:
      - FelixKratz/formulae
      - homebrew/cask-fonts

    homebrew_cask_apps:
      - alt-tab
      - bartender
      - betterdisplay # more display options
      - calibre
      - cleanshot # screen recording
      - docker
      - firefox
      - font-hack-nerd-font
      - forklift # finder alternative
      - google-cloud-sdk
      - google-chrome
      - handbrake
      - iterm2
      - karabiner-elements
      - keycastr
      - kitty
      - keepassxc
      - libreoffice
      - macfuse # dependecy of telepresence
      - middle
      - min # minimal browser with no distractions
      - mouse-fix # fix scrolling for external mice
      - numi
      - postman
      - stats
      - syncthing
      - skim # pdf viewer for vim-latex
      - vscodium

    homebrew_cask_uninstalled_apps: []

    # vars for ansible-role-pip
    pip_packages:
      # - "molecule[docker]"
      # - molecule pynacl build fails
      - pytest-testinfra
      - selenium

    # vars for ansible-role-binaries
    # these are apps that are either not available with brew
    # or I require a fixed version
    kubectl_version: 1.22.0
    pet_version: 0.4.0
    tfswitch_version: 0.13.1300
    goMarkableClient_version: 0.6.4
    kustomize_version: v4.5.7
    binaries:
      - name: kustomize
        url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F{{ kustomize_version }}/kustomize_{{ kustomize_version }}_darwin_arm64.tar.gz
        extract: true
      - name: kubectl
        url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/darwin/arm64/kubectl"
      - name: pet
        url: "https://github.com/knqyf263/pet/releases/download/v{{ pet_version }}/pet_{{ pet_version }}_darwin_arm64.tar.gz"
        extract: true
      - name: tfswitch
        url: "https://github.com/warrensbox/terraform-switcher/releases/download/{{tfswitch_version}}/terraform-switcher_{{tfswitch_version}}_darwin_arm64.tar.gz"
        extract: true
      - name: gh-md-toc
        url: "https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc"
        extract: false
      - name: goMarkableClient
        url: "https://github.com/owulveryck/goMarkableStream/releases/download/v{{goMarkableClient_version}}/goMarkableClient_{{goMarkableClient_version}}_Darwin_arm64.tar.gz"
        extract: true
      # NOTE: No developing anymore
      - name: remouseable
        url: "https://github.com/kevinconway/remouseable/releases/download/v0.4.0/osx"
        bin_name: osx
        extract: false

  tasks:
    - import_tasks: tasks/osx.yml

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - ansible-role-dotfiles
    - ansible-role-pip
    - ansible-role-binaries
